### PR TITLE
Fix/ List Collections items prop removed

### PR DESCRIPTION
**Pull request by msalvatti**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @friggframework/api-module-frontify@1.0.1-canary.212.6fb55c8.0
  # or 
  yarn add @friggframework/api-module-frontify@1.0.1-canary.212.6fb55c8.0
  ```
</details>

### CODE REVIEW

**Review by leofmds — CHANGES_REQUESTED** [review]
Just noting the test for listCollections function is misleading and needs to be updated since this return was changed.

The items always returns an array, and the test is returning a single object. 
Check line 1175 from api.test.js and update the tests accordingly

**Review by leofmds — CHANGES_REQUESTED** [review]
@maxsalvatti this mock is still wrong. The return from the endpoint shows an array, and this is an object. If this endpoint returns an array only if we have two or more results, then we should treat those cases as well.

`data: {
                                library: {	                                library: {
                                    collections: {	                                    collections: {
                                        items: {	                                        items: {
                                            id: 'id',	                                            id: 'id',
                                            name: 'Test collection',	                                            name: 'Test collection',
                                            __typename: 'Collection'	                                            __typename: 'Collection'
                                        }	                                        }
                                    }	                                    }
                                }	                                }
                            }	                            }`

**Review by leofmds — APPROVED** [review]
👍🏻

**Comment by seanspeaks** [comment]
:rocket: PR was released in [`@friggframework/api-module-frontify@1.0.1`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-frontify%401.0.1) :rocket:

**Pull request merged**
