### PR TITLE
Fix/Frontify refresh token url fixed

### PR DESCRIPTION
**Pull request by msalvatti**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @friggframework/api-module-frontify@1.1.2-canary.226.6bf1ba9.0
  # or 
  yarn add @friggframework/api-module-frontify@1.1.2-canary.226.6bf1ba9.0
  ```
</details>

### CODE REVIEW

**Review by seanspeaks — CHANGES_REQUESTED** [review]
I'm opposed to making this change on the OAuth2Requester class, as it will break all other oauth2 api modules, and the OAuth2 spec suggests a single token endpoint should be built by the provider. Frontify breaking from the spec should mean customizing the Frontify API module class.

So, override the refreshToken method on the api class instead (just making that one change)

Can you also include an api.test.js update?

**Review by seanspeaks — APPROVED** [review]
I was looking for integration tests, actually confirming the access token refresh function is working with the Frontify API, but we can punt to later iterations 👌

**Comment by seanspeaks** [comment]
:rocket: PR was released in [`@friggframework/api-module-frontify@1.1.2`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-frontify%401.1.2) :rocket:

**Comment by msalvatti** [comment]
> I was looking for integration tests, actually confirming the access token refresh function is working with the Frontify API, but we can punt to later iterations 👌

@seanspeaks I tried to implement the test but without success, I will check how to do it and implement it in a new task.

**Comment by seanspeaks** [comment]
Sounds good- feel free to ping @MichaelRyanWebber too to help troubleshoot, he's done a few of them

**Pull request merged**
