### PR TITLE
Fix Slack getChannelHistory call

### PR DESCRIPTION
**Pull request by debbie-yu**
Slack API always returns 200 status regardless if error.

Based on https://api.slack.com/methods/conversations.history, it looks like we should be calling with `application/x-www-form-urlencoded` Content-Type header

Looks like I'm not able to verify if slack test are passing. Will try out in ironclad-frigg to verify

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @friggframework/api-module-hubspot@0.8.27-canary.147.2e4d710.0
  npm install @friggframework/api-module-slack@0.1.32-canary.147.2e4d710.0
  npm install @friggframework/integrations@1.0.24-canary.147.2e4d710.0
  # or 
  yarn add @friggframework/api-module-hubspot@0.8.27-canary.147.2e4d710.0
  yarn add @friggframework/api-module-slack@0.1.32-canary.147.2e4d710.0
  yarn add @friggframework/integrations@1.0.24-canary.147.2e4d710.0
  ```
</details>

### CODE REVIEW

**Review by seanspeaks — APPROVED** [review]
Should work... a bit concerned about using 'application/x-www-form-urlencoded' just for this one request, but for "does it work", LGTM

(consider this a "TODO" of "get it working with json"... I had it working in Postman with JSON, hence my note)

**Comment by debbie-yu** [comment]
> Should work... a bit concerned about using 'application/x-www-form-urlencoded' just for this one request, but for "does it work", LGTM
> 
> (consider this a "TODO" of "get it working with json"... I had it working in Postman with JSON, hence my note)

@seanspeaks yeah i still find it strange why the second would apparently work but it seems like for some reason first call always complains about required field `channel` missing. i think with `application/x-www-form-urlencoded` seems to expect body in certain format. not sure about other slack api's but it looks like at least for this one it expects this content-type

**Comment by seanspeaks** [comment]
:rocket: PR was released in [`@friggframework/api-module-slack@0.1.32`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-slack%400.1.32), [`@friggframework/integrations@1.0.24`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/integrations%401.0.24) :rocket:

**Comment by seanspeaks** [comment]
:rocket: PR was released in [`@friggframework/api-module-slack@0.1.33`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-slack%400.1.33) :rocket:

**Pull request merged**
