### PR TITLE
Add ECONNRESET update

### PR DESCRIPTION
**Pull request by seanspeaks**
Ditto here.

@MichaelRyanWebber Do I need to label as release and patch? Or is the release label a nono?

### CODE REVIEW

**Review by leofmds — APPROVED** [review]
LGTM

**Comment by MichaelRyanWebber** [comment]
> Ditto here.
> 
> @MichaelRyanWebber Do I need to label as release and patch? Or is the release label a nono?

The release label won't be relevant. Patch is good.

**Review by MichaelRyanWebber — APPROVED** [review]
looks good

**Comment by seanspeaks** [comment]
:rocket: PR was released in [`@friggframework/api-module-activecampaign@0.11.1`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-activecampaign%400.11.1), [`@friggframework/api-module-airwallex@0.11.1`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-airwallex%400.11.1), [`@friggframework/api-module-attentive@0.11.1`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-attentive%400.11.1), [`@friggframework/api-module-clyde@0.11.1`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-clyde%400.11.1), [`@friggframework/api-module-connectwise@0.11.1`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-connectwise%400.11.1), [`@friggframework/api-module-crossbeam@0.11.1`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-crossbeam%400.11.1), [`@friggframework/api-module-fastspring-iq@0.11.1`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-fastspring-iq%400.11.1), [`@friggframework/api-module-front@0.11.1`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-front%400.11.1), [`@friggframework/api-module-frontify@1.3.1`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-frontify%401.3.1), [`@friggframework/api-module-google-calendar@0.3.1`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-google-calendar%400.3.1), [`@friggframework/api-module-google-drive@0.3.2`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-google-drive%400.3.2), [`@friggframework/api-module-gorgias@0.11.1`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-gorgias%400.11.1), [`@friggframework/api-module-hubspot@0.11.1`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-hubspot%400.11.1), [`@friggframework/api-module-huggg@0.11.1`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-huggg%400.11.1), [`@friggframework/api-module-ironclad@0.3.1`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-ironclad%400.3.1), [`@friggframework/api-module-marketo@0.11.1`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-marketo%400.11.1), [`@friggframework/api-module-microsoft-sharepoint@0.3.1`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-microsoft-sharepoint%400.3.1), [`@friggframework/api-module-microsoft-teams@0.4.2`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-microsoft-teams%400.4.2), [`@friggframework/api-module-monday@0.11.1`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-monday%400.11.1), [`@friggframework/api-module-netx@0.11.1`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-netx%400.11.1), [`@friggframework/api-module-outreach@0.11.1`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-outreach%400.11.1), [`@friggframework/api-module-personio@0.11.1`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-personio%400.11.1), [`@friggframework/api-module-pipedrive@0.11.1`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-pipedrive%400.11.1), [`@friggframework/api-module-qbo@0.11.1`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-qbo%400.11.1), [`@friggframework/api-module-rev-io@0.11.1`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-rev-io%400.11.1), [`@friggframework/api-module-rollworks@0.11.1`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-rollworks%400.11.1), [`@friggframework/api-module-salesforce@0.11.1`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-salesforce%400.11.1), [`@friggframework/api-module-salesloft@0.11.1`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-salesloft%400.11.1), [`@friggframework/api-module-slack@0.4.1`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-slack%400.4.1), [`@friggframework/api-module-terminus@0.11.1`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-terminus%400.11.1), [`@friggframework/api-module-yotpo@0.3.1`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-yotpo%400.3.1), [`@friggframework/api-module-zoom@0.11.1`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/api-module-zoom%400.11.1), [`@friggframework/integrations@1.2.3`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/integrations%401.2.3), [`@friggframework/module-plugin@1.1.3`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/module-plugin%401.1.3), [`@friggframework/types@0.2.3`](https://github.com/friggframework/frigg/releases/tag/%40friggframework/types%400.2.3) :rocket:

**Pull request merged**
